package:
  name: yt
  version: 3.3dev

source:
  url: https://bitbucket.org/yt_analysis/yt/get/dda861e88caf.zip
  sha256: 1b6686938e06dc9346de84e90ff5aa63a4c2471c2f7ec54fd82a35e38755dcaa

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy x.x
    - cython >=0.24.0
    - setuptools >=19.6
  run:
    - setuptools
    - python
    - numpy x.x
    - h5py
    - sympy
    - matplotlib
    - ipython

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD 3-clause
  summary: Analysis and visualization toolkit for volumetric data

extra:
    recipe-maintainers:
      - ngoldbaum
      - xarthisius
