{% set version = "4.4.1" %}

package:
  name: yt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/y/yt/yt-{{ version }}.tar.gz
  sha256: 2df36425b48321ca236ea638f64fbe834f5d3b47c948cd519a7b048686253c25
  patches:
    - patches/force_cythonize.patch
    - patches/crossc-openmp.patch  # [linux]
    - patches/drop_iyt.patch  # [python_impl == 'pypy']

build:
  number: 2
  python_version_independent: true  # [py>=311 and is_abi3]
  entry_points:
    - yt = yt.utilities.command_line:run_main
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - OMP_NUM_THREADS=1
    - MAX_BUILD_CORES=2
    - YT_LIMITED_API=1
  skip: true  # [py>=312 and is_abi3]

requirements:
  build:
    - python-abi3                            # [py>=311 and is_abi3]
    - cython <3.1                            # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgomp                                # [linux]
    - ewah-bool-utils >=1.0.2                # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - numpy
    - cython >=3.0.3,<3.1
    - ewah-bool-utils >=1.0.2
    - setuptools >=61.2
  run:
    - python
    - ipywidgets >=8.0.0
    - matplotlib-base !=3.4.2,>=3.2.0
    - more-itertools >=8.4
    - packaging >=20.9
    - pillow >=6.2.1
    - tomli >=1.2.3  # [py<311]
    - tomli-w >=0.4.0
    - tqdm >=3.4.0
    - unyt >=2.9.2
    - cmyt >=1.1.2
    - ewah-bool-utils >=1.0.2
    - typing-extensions >=4.1.0  # [py<311]

test:
  imports:
    - yt
  commands:
    - pip check
    - yt --help
    - abi3audit $SP_DIR/yt/*.abi3.so -s -v --assume-minimum-abi3 3.11  # [unix and py>=311 and is_abi3]
  requires:
    - pip
    - abi3audit  # [py>=311 and is_abi3]

about:
  home: http://yt-project.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Analysis and visualization toolkit for volumetric data

extra:
  recipe-maintainers:
    - matthewturk
    - munkm
    - xarthisius
