{% set version = "4.4.0" %}

package:
  name: yt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/y/yt/yt-{{ version }}.tar.gz
  sha256: 0e15df9cb21abe582f8128bf0705a3bc0f4805f97efd6b4f883073703941c0d5
  patches:
    - patches/force_cythonize.patch
    - patches/crossc-openmp.patch  # [linux]
    - patches/drop_iyt.patch  # [python_impl == 'pypy']

build:
  number: 2
  skip: true  # [py<310 or python_impl == 'pypy']
  entry_points:
    - yt = yt.utilities.command_line:run_main
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - OMP_NUM_THREADS=1
    - MAX_BUILD_CORES=2

requirements:
  build:
    - cython <3.1                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgomp                                # [linux]
    - ewah-bool-utils >=1.0.2                # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - numpy
    - cython >=3.0.3,<3.1
    - ewah-bool-utils >=1.0.2
    - setuptools >=61.2
  run:
    - python
    - ipywidgets >=8.0.0
    - matplotlib-base !=3.4.2,>=3.2.0
    - more-itertools >=8.4
    - packaging >=20.9
    - pillow >=6.2.1
    - tomli >=1.2.3  # [py<311]
    - tomli-w >=0.4.0
    - tqdm >=3.4.0
    - unyt >=2.9.2
    - cmyt >=1.1.2
    - ewah-bool-utils >=1.0.2
    - typing-extensions >=4.1.0  # [py<311]

test:
  imports:
    - yt
  commands:
    - pip check
    - yt --help
  requires:
    - pip

about:
  home: http://yt-project.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Analysis and visualization toolkit for volumetric data

extra:
  recipe-maintainers:
    - matthewturk
    - munkm
    - xarthisius
