{% set version = "4.0.0" %}

package:
  name: yt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yt/yt-{{ version }}.tar.gz
  sha256: 44054b91a51755213da3891b9da53ec2b8976c1a4c39af395497d10afe278074

build:
  number: 0
  entry_points:
    - yt = yt.utilities.command_line:run_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.24.0
  run:
    - python
    - ipython >=1.0
    - matplotlib-base >=1.5.3
    - numpy >=1.13.3
    - packaging >=20.9
    - pyyaml >=4.2b1
    - setuptools >=19.6
    - sympy >=1.2
    - toml >=0.10.2
    - tqdm >=3.4.0
    - unyt >=2.8.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - yt
  commands:
    - pip check
    - yt --help
  requires:
    - pip

about:
  home: http://yt-project.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Analysis and visualization toolkit for volumetric data

extra:
  recipe-maintainers:
    - ngoldbaum
    - munkm
