{% set version = "3.6.0" %}
{% set sha256 = "effb00536f19fd2bdc18f67dacd5550b82066a6adce5b928f27a01d7505109ec" %}

package:
  name: yt
  version: {{ version }}

source:
  fn: yt-{{ version }}.tar.gz
  url: http://yt-project.org/sdist/yt-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python setup.py -q install --single-version-externally-managed --record=record.txt
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - cython >=0.24.0
    - setuptools >=19.6
  run:
    - setuptools
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - sympy
    - matplotlib-base
    - ipython

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Analysis and visualization toolkit for volumetric data

extra:
  recipe-maintainers:
    - ngoldbaum
    - munkm
