appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: SES8G3RzEYZq91t3MB4AAy1V7WQllcPMCwjXOcUd9z79iicZuLKfkvlYIQLfH6InR4j/1UkOgL1uld0EmVkdQvkk8e/quhTIAI8bc7XjDJYWNaQYxriGAqVOKvT2+s5T+jknfFVWudpJw6SAa9eDMoFCpBdETiepeKkjoBp239IcdplRgmWWxxuCruHOY/k4eisvKjeJkaSiyIDRK0F0qQ9yvkTIo6GcvxHj7weI6NS/yqr659vSh1d1fhDzvLizB0vzhBuqJrkTAIjSqSyHuehZ/NJwz3bbSIyGwmPjgs2zcjr1TVtXYioVQq7KWpLOs5mKMNLAJf+NIcB4nb8UavfG+Lw+vK5S5930peT91AazomO78xfPGTQ2ZKTh7dQA3Hv2HpJO3JVi0xvr7iT2K7da4imB/a8SbPVB29g0DVzldnGCdpp0FNzwn+mPoNTWjDBUipVbK3IFqobuG+fmIDt/D9GnKW91S/DTJdwMw7cMTxnsONp+CcyztMq9kOeKesyt5xXliVO3CzunAuzv3Lq7AIdlgc167NbyQHLq2tcaJ8/3rdaDcuu0Vj887/gRg+x2MPztmZa6j3XxEJQyU5spt6Yc/6ASurRZP7VqmUolttZSj0cHnoHMKk5hWge0pRtgPRCRBmxKjZv/nT8CV68i7Nu90m8m6qO7TRxncfg=}
